### ISSUE TITLE
Basic Routing Setup

### ISSUE THREAD

**Issue by ronnieoverby** [bn3t/generator-ngx-firebase-bootstrap#4]
A basic routing setup would go a long way in this generator.

Good work, all the same.

**Comment by bn3t** [comment]
Thanks for your feedback. Can you have a look at the feature/use-router branch in this repo and tell me if you like it this way?

**Comment by ronnieoverby** [comment]
Looks good. One improvement that I've made in my own app is to have `AuthService` implement CanActivate (just return isLoggedIn`).

Then you can use the auth service to prevent routing to a protected route.

**Comment by bn3t** [comment]
Would you care submitting a pull request?

**Comment by bn3t** [comment]
Nevermind, I've seen your project smeddit. I can alway take inspiration of that.

**Comment by bn3t** [comment]
The router setup is finally finalized and available on npm since version 2.1.0.
