### ISSUE TITLE
You have to be inside an angular-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by totallytotallyamazing** [bn3t/generator-ngx-firebase-bootstrap#5]
**When I type the command "ng serve" the following error appears, "You have to be inside an angular-cli project in order to use the serve command."
Do you have any Idea why this may be happening?
I'm using the following:**
**Thank you bn3t !**
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: darwin x64
mys-iMac:~ my$ 
________________________________
**Also I'm getting some UNMET PEAR DEPENDENCIES when generating a new project:**

yoang2firebaseboot
├─┬ @angular/cli@1.0.0 
...
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.10
...
├── UNMET PEER DEPENDENCY @angular/core@2.4.10
...
├─┬ UNMET PEER DEPENDENCY tslint@4.2.0
...
└── zone.js@0.7.6 

npm WARN codelyzer@1.0.0-beta.4 requires a peer of tslint@^3.9.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.

mys-iMac:yoang2firebaseboot my$ ng serve

You have to be inside an angular-cli project in order to use the serve command.
mys-iMac:yoang2firebasebootmy$

**Comment by bn3t** [comment]
Please update your angular cli to the latest version. It is now @angular/cli. Please see https://github.com/angular/angular-cli/wiki/stories-1.0-update for instructions for updating.

**Comment by bn3t** [comment]
Thanks for the nice comment. Enjoy.
