### ISSUE TITLE
Cannot find module 'ng2-bootstrap'

### ISSUE THREAD

**Issue by reikjarloekl** [bn3t/generator-ngx-firebase-bootstrap#6]
Apparently the reference to ng2-bootstrap is outdated. I am receiving the following error messages when trying to `ng serve` the project.

> ERROR in C:/work/meisterwerk/midge/web-app/src/app/app.module.ts (14,27): Cannot find module 'ng2-bootstrap'.
> ERROR in C:/work/meisterwerk/midge/web-app/src/app/app.component.spec.ts (7,27): Cannot find module 'ng2-bootstrap'.`

After changing the references in those two files to 'ngx-bootstrap' the project compiles without problems.

Also see https://www.npmjs.com/package/ng2-bootstrap

> this package was renamed to ngx-bootstrap

**Comment by bn3t** [comment]
Merged. Thanks!
