### ISSUE TITLE
No 'dist' as public directory - not deploying

### ISSUE THREAD

**Issue by mrmccormack** [bn3t/generator-ngx-firebase-bootstrap#8]
Everything worked perectly on localhost, 
but I don't get the same index file after deploying.

Q:
Are you sure  **'dist'** folder  is correct.

Thanks for great software.
Rob

**From instructions:**

In a nutshell:

```
$ firebase init
 
> Choose Hosting
> Accept default database.rules.json
> Choose 'dist' as your public directory
> Enter 'yes' for rewrite all urls to index.html

```

**Comment by bn3t** [comment]
Hi Rob,
Thanks for the nice feedback and for creating this issue.
The dist folder is fine, the problem is that there is a problem running ng build for prod with aot. I am currently looking at it and fixing it.
Stay tuned.

**Comment by santosh719** [comment]
Hi,

I'm also facing the same issue. Is there any temporary fix for this?

By the way, awesome generator!

**Comment by bn3t** [comment]
The version 2.1.4 that I just published should fix the issue. Please tell me if you have more success with this one.
@santosh719: Thanks for the feedback as well, I appreciate it. Please star the project as well, it's important.
